### ISSUE TITLE
PDF Reading Error

### ISSUE THREAD

**Issue by danilolutz** [okfn-brasil/diario-oficial#104]
Hello guys.

Just to report...

Accidentally I found this mistake caused by decimal places: dot and comma stuff. 

This is the PDF content:
![diario3](https://user-images.githubusercontent.com/1561739/44063028-26d8174e-9f35-11e8-9b72-cdcc76a9ce06.png)

http://dopaonlineupload.procempa.com.br/dopaonlineupload/1318_ce_20150119_executivo.pdf

And this image bellow it's we have on https://diario.serenata.ai
![diario2](https://user-images.githubusercontent.com/1561739/44062728-04b72430-9f34-11e8-98af-6b23df665f77.png)

Hope it's help...

See you guys...

**Comment by pauloabelha** [comment]
God to know. This task of extraction has been proving itself highly non-trivial... That's what makes it challenging and fun,and important! :)

**Comment by Irio** [comment]
Hi @danilolutz, the code for parsing bidding exemptions is not part of the project anymore (please see https://github.com/okfn-brasil/diario-oficial/commit/b575ed159330572f5a0de3612e44a985835cf0a3). In this case, I am closing this issue.
