### ISSUE TITLE
Should we extract "Inexigibilidade de licitação" as well?

### ISSUE THREAD

**Issue by vitorbaptista** [okfn-brasil/diario-oficial#108]
While working on #106, I found a few "inexigibilidade de licitação", which seems to be cases where there is only one supplier (e.g. artists for concerts). For example, see page 5 on http://www.diariooficial.feiradesantana.ba.gov.br/atos/executivo/12L2UO1692015.pdf. Would we like to extract it as well?

**Comment by giovanisleite** [comment]
I had the same question, it was answered [here](https://github.com/okfn-brasil/diario-oficial/issues/36).
I think this type of documents could bring problems not just related to value, but with the type of service as well (when we know that there is more than one supplier).

**Comment by vitorbaptista** [comment]
@giovanisleite Thanks for the link! So, bottom line is: yes? If so, maybe we should add this information to the `CONTRIBUTING.md` file?

**Comment by cuducos** [comment]
> Thanks for the link! So, bottom line is: yes?

Yep : )

Thanks @vitorbaptista and @giovanisleite

**Comment by vitorbaptista** [comment]
Great! Sent a small PR to add this information to CONTRIBUTING.md.
