### ISSUE TITLE
https://diario.serenata.ai is currently offline

### ISSUE THREAD

**Issue by vitorbaptista** [okfn-brasil/diario-oficial#114]
Apparently, the `diario-api` service is offline. This is the result from `curl https://diario.serenata.ai`:

```json
{
  "status": 500,
  "message": "getaddrinfo ENOTFOUND diario-api diario-api:3000",
  "name": "NuxtServerError"
}
```

**Comment by jonjoncardoso** [comment]
The service seems to be online now but it complains of an invalid certificate:

     curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
     More details here: http://curl.haxx.se/docs/sslcerts.html

    curl performs SSL certificate verification by default, using a "bundle" of Certificate Authority (CA) public keys (CA certs). If the default  bundle file isn't adequate, you can specify an alternate file using the --cacert option.
    If this HTTPS server uses a certificate signed by a CA represented in the bundle, the certificate verification probably failed due to a  problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
    If you'd like to turn off curl's verification of the certificate, use the -k (or --insecure) option.

**Comment by thiagoalmeidasa** [comment]
This service is running on top of docker container, right?

If you use `docker-compose` to run this in production, please share the output of `docker-compose ps` in the production environment.

**Comment by willianpaixao** [comment]
Maybe you can also share the output of `docker-compose logs` if possible.

**Comment by benmezger** [comment]
That's because the SSL certificate has been created without giving a Subject Alternative name (meaning it has no domain name), so the browser cannot verify it. If you check the name it's set to `letsencrypt-nginx-proxy-companion`.

**Comment by Irio** [comment]
I talked to @ncortezrj and @sergiomario to understand @okfn-brasil's roadmap for the following months. At least for the soon future, there are no plans of parsing and showing bidding exemptions in a website.

This plan is initially reflected in https://github.com/okfn-brasil/diario-oficial/pull/131, especially in https://github.com/okfn-brasil/diario-oficial/commit/b575ed159330572f5a0de3612e44a985835cf0a3.
