### ISSUE TITLE
Apache Tika

### ISSUE THREAD

**Issue by jvanz** [okfn-brasil/diario-oficial#136]
Try to use the Apache Tika to extract data from DOC and PDF files. Replacing the current pipeline steps to extract the text from the downloaded files

**Comment by jvanz** [comment]
I've decided to open this issue after a discussion about how extract text from the file in the PR https://github.com/okfn-brasil/diario-oficial/pull/135

**Comment by vitorbaptista** [comment]
Whenever someone works on this, if you change the code to let Tika also handle the PDFs, make sure you're not reducing the quality of the extracted text. I'd go as far as keeping the current PDF handling procedure intact, as I imagine the parsers can be very brittle and end up breaking if the text extracted from PDFs changes format.

**Comment by jvanz** [comment]
https://github.com/okfn-brasil/diario-oficial/commit/399179c7a740c0d378a14417fc7050bf0f23a6f2
