### ISSUE TITLE
Upload scraped files to digital ocean

### ISSUE THREAD

**Issue by jvanz** [okfn-brasil/diario-oficial#165]
Creates a pipeline item to upload the scrapped files to the Digital Ocean spaces. 

Related to issue #157

**Comment by rennerocha** [comment]
I don`t consider an item pipeline the best way to achieve this. A new storage backend and maybe a new feed exporter depending on the format you want (like the one that stores the output in S3) seems to be a better solution. https://docs.scrapy.org/en/latest/topics/feed-exports.html#storage-backends

If you use a pipeline, you can put another pipeline by mistake after the one that uploads the data to Digital Ocean and you will lose the changes that the new pipeline does in your data.

**Comment by jvanz** [comment]
> you use a pipeline, you can put another pipeline by mistake after the one that uploads the data to Digital Ocean and you will lose the changes that the new pipeline does in y

Cool, you're right. I'll do that. By the way, if we decided to use Digital Ocean spaces (very similar to the S3), IFAIK it uses the same S3 protocol. Thus, maybe it is possible to use the S3 exporter. But I need to validate that.

**Comment by jvanz** [comment]
@rennerocha, `FilesPipeline` allows us to download the file and upload them to S3 using the storage backed. However, there is a problem. To make it work with the Digital Ocean Spaces I need to set a custom endpoint url and I cannot change that configuration via environment variable. Furthermore, I did not find any workaround yet. Is there a way to define a custom storage backend for `FilePipeline`? Thus, I can adapt it to work with D.O. Spaces.

**Comment by jvanz** [comment]
The boto3 configuration which I need to change can be modify using scrapy settings. As the Digital Ocean spaces can be access using the S3 protocol, this can be close the issue. The `FilesPipeline` already allow the user to store the files in a remote storage systems, like S3.
