### ISSUE TITLE
Natal spider

### ISSUE THREAD

**Issue by jvanz** [okfn-brasil/diario-oficial#189]
Add spider for Natal

**Comment by victor-torres** [comment]
I can help with this spider. I live in Natal and I have experience with Scrapy.

**Comment by fredericopranto** [comment]
> I can help with this spider. I live in Natal and I have experience with Scrapy.

Great! Please join in this discord (https://discord.gg/9YRZADs). We can help too.

**Comment by victor-torres** [comment]
Hi @fredericopranto, how is this project related to the okfn-brasil org?

**Comment by fredericopranto** [comment]
It`s not, directly. Its only a community group to discuss open data at Rio Grande do Norte. Feel free to join.
