### ISSUE TITLE
Lista das 100 maiores municípios do Brasil

### ISSUE THREAD

**Issue by pedrro** [okfn-brasil/diario-oficial#21]
Oi pessoal, quero começar a contribuir no projeto pegando uma cidade para fazer o scrapy, porém, no site não existe informação sobre quais são os municípios _target_, apenas que são as 100 maiores do Brasil, mas baseado em que? Habitantes, PIB, etc...

**Comment by Irio** [comment]
Nos interessamos pelos 100 municípios com maior população, @pedrro. A lista completa pode ser vista aqui: https://pt.wikipedia.org/wiki/Lista_de_municípios_do_Brasil_por_população

**Comment by Irio** [comment]
Com sorte, esse commit vai responder essa pergunta para outras pessoas do futuro: https://github.com/okfn-brasil/diario-oficial/commit/ebbe2e1274332075383e57f925b567de1785544a

**Comment by gustavodemari** [comment]
Talvez seria interessante ter a lista com os munícipios e junto com um status de implementação.

Isso poderia ajudar as pessoas a pegarem munícipios que ainda não foram implementados e também para usarem os munícipios já implementados como um "guia".

**Comment by cuducos** [comment]
> Talvez seria interessante ter a lista com os munícipios e junto com um status de implementação.

Esses dias [fiz isso](https://gist.github.com/cuducos/748d5269055e18cf2acbebc6e02ed22e) só de curiosidade. Acho que tem que atualizar com os dados dos últimos 3 dias, mas pode ser um começo…
