### ISSUE TITLE
Period of interest

### ISSUE THREAD

**Issue by giovanisleite** [okfn-brasil/diario-oficial#23]
Some of the spiders are limited to get documents from the current year till 2014.
This rule must be applied to all spiders?

**Comment by Irio** [comment]
Based on existing explorations, it seems that 2015+ (2015 included) is a good start - couple years from the previous administration term, and at least one from the current one. How others feel about that?

**Comment by brunolellis** [comment]
Sounds good to me

**Comment by Irio** [comment]
Added to CONTRIBUTING file. https://github.com/okfn-brasil/diario-oficial/commit/1a61d7b8e77193d4f2d8ed301c4ce56c44806e1f
