### ISSUE TITLE
Dispensa de licitação e Inexigibilidade

### ISSUE THREAD

**Issue by giovanisleite** [okfn-brasil/diario-oficial#36]
Acham válida a ideia de localizarmos, além das dispensas, as inexigibilidades também?

“A diferença básica entre as duas hipóteses está no fato de que, na dispensa, há possibilidade de competição que justifique a licitação; de modo que a lei faculta a dispensa, que fica inserida na competência discricionária da Administração. Nos casos de inexigibilidade, não há possibilidade de competição, porque só existe um objeto ou uma pessoa que atenda às necessidades da Administração; a licitação é, portanto, inviável”.
DI PIETRO, Maria Sylvia Zanella., Direito administrativo. 14. ed. São Paulo: Atlas, 2002, p. 310, 320-321.
[Fonte](http://www.ambito-juridico.com.br/site/index.php?n_link=revista_artigos_leitura&artigo_id=7788#_ftn4)

**Comment by Irio** [comment]
Vi que inexigilidades muitas vezes são publicadas com o título "dispensa de licitação" (que não deixa de ser uma dispensa também), diferenciando apenas no artigo da lei de licitações argumentado pelo gestor. Me parece válido sim, @giovanisleite.
