### ISSUE TITLE
Change spider to allow select date/period of the items

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/diario-oficial#39]
Actually when executing the spiders all available gazettes are retrieved. This could be a waste of resources as the data extracted (the gazette) doesn't change.

I had a quick discussion with @Irio , and he suggested the following options:
1. Include a parameter indicating the start date that the spider should collect the gazettes;
2. Check the database to identify when was the last gazette collected, and then collect everything after that.

**Comment by rennerocha** [comment]
I tend to prefer a solution that reduces the connection with external services (like a database with the existing downloaded gazettes). In my opinion, the user that triggers the execution of the spider is the one that knows which dates needs to be scraped.

**Comment by rennerocha** [comment]
@Irio , I was reading the comments in #23 and I was wondering, do you think it is interesting to specify a default start date for the base spider, so by default all spiders will get only items after this date?

**Comment by Irio** [comment]
@rennerocha How about each spider declare the first date where a gazette is available and have the default starting date to be 2015-01-01 (when available)?

**Comment by rennerocha** [comment]
@Irio We could include a default start_date here (equal to 2015-01-01), so every spider created will have this date as inferior limit by default:
https://github.com/okfn-brasil/diario-oficial/pull/41/files#diff-4e2c9f569e945a46b8421f7e510b1d91R8

I don't see the need for each spider to include its own dates, as we will guarantee that this limit will be followed by any spider.

What do you think?

**Comment by cuducos** [comment]
> I don't see the need for each spider to include its own dates

Maybe it's relevant when a gazette's initial date is later than 2015-01-01. Then we could use something like `min(self.START_DATE, self.AVAILABLE_SINCE)` where `self.START_DATE` would be 2015-01-01 and `self.AVAILABLE_SINCE` something like `2016-07-22`…

**Comment by Irio** [comment]
I was suggesting to have each spider declare state its first available date so we could raise an exception if the input comes before. Eather way sounds good to me.

**Comment by cuducos** [comment]
Many thanks! This is indeed important:

> Maybe we should not restrict the spiders to get all available gazettes because we want this date limitation now, but in future we may want to change this limitation (for example, if we found a way to do a new kind of analysys in older gazettes). With more than 100 spiders) it will be very difficult to change it everywhere.

**Comment by rennerocha** [comment]
So should we insert a default `start_date` as 2015-01-01 in the base spider?
There is an open PR (https://github.com/okfn-brasil/diario-oficial/pull/46) that makes all existing spider to inherit from this class, so it will require just one line of code.

**Comment by Irio** [comment]
Closing since the idea was already implemented by #46.
