### ISSUE TITLE
Cities

### ISSUE THREAD

**Issue by alfakini** [okfn-brasil/diario-oficial#48]
Hey people,

Adding @cuducos [work in progress tracking](https://gist.github.com/cuducos/748d5269055e18cf2acbebc6e02ed22e) here to help us keep track of the work to be done.

:white_check_mark: Done
:soon: In progress

| # | Cidade | Crawler | Parser | Issue | PR |
|:-:|--------|:-------:|:------:|:------:|:------:|
| 1 | São Paulo | | | https://github.com/okfn-brasil/diario-oficial/issues/7 | |
| 2 | Rio de Janeiro | :soon: | | https://github.com/okfn-brasil/diario-oficial/issues/15 | https://github.com/okfn-brasil/diario-oficial/pull/29 |
| 3 | Brasília | | | | |
| 4 | Salvador | | | | https://github.com/okfn-brasil/diario-oficial/pull/47 |
| 5 | Fortaleza | :soon: | | | https://github.com/okfn-brasil/diario-oficial/pull/52 |
| 6 | Belo Horizonte | | | | https://github.com/okfn-brasil/diario-oficial/pull/33 |
| 7 | Manaus | :soon:  | | | https://github.com/okfn-brasil/diario-oficial/pull/51 |
| 8 | Curitiba | | | | https://github.com/okfn-brasil/diario-oficial/pull/42 |
| 9 | Recife | :soon: | | | |
| 10 | Porto Alegre | :white_check_mark: | :white_check_mark: | | |
| 11 | Goiânia | :white_check_mark: | :soon: | | https://github.com/okfn-brasil/diario-oficial/pull/6 |
| 12 | Belém | | | | |
| 13 | Guarulhos | :white_check_mark: | | | https://github.com/okfn-brasil/diario-oficial/pull/4 |
| 14 | Campinas | :white_check_mark: | | | https://github.com/okfn-brasil/diario-oficial/pull/2 |
| 15 | São Luís | :soon: | | | https://github.com/okfn-brasil/diario-oficial/pull/22 |
| 16 | São Gonçalo | | | | |
| 17 | Maceió | :soon: | | | https://github.com/okfn-brasil/diario-oficial/pull/32 |
| 18 | Duque de Caxias | | | | |
| 19 | Natal | | | | |
| 20 | Campo Grande | | | | https://github.com/okfn-brasil/diario-oficial/pull/35 |
| 21 | Teresina | :soon: | | | https://github.com/okfn-brasil/diario-oficial/pull/53 |
| 22 | São Bernardo do Campo | | | | |
| 23 | João Pessoa | | | | |
| 24 | Nova Iguaçu | | | | |
| 25 | Santo André | | | | |
| 26 | São José dos Campos | | | | |
| 27 | Osasco | | | | |
| 28 | Jaboatão dos Guararapes | | | | |
| 29 | Ribeirão Preto | | | https://github.com/okfn-brasil/diario-oficial/issues/31 | |
| 30 | Uberlândia | | | | https://github.com/okfn-brasil/diario-oficial/pull/37 |
| 31 | Sorocaba | | | | |
| 32 | Contagem | | | | |
| 33 | Aracaju | | | | |
| 34 | Feira de Santana | :soon: | | | https://github.com/okfn-brasil/diario-oficial/pull/25 |
| 35 | Cuiabá | | | | |
| 36 | Joinville | :soon: | | | https://github.com/okfn-brasil/diario-oficial/pull/30 |
| 37 | Juiz de Fora | :soon: | | https://github.com/okfn-brasil/diario-oficial/issues/12 | https://github.com/okfn-brasil/diario-oficial/pull/13 |
| 38 | Londrina | | | | |
| 39 | Aparecida de Goiânia | | | | |
| 40 | Porto Velho | | | | |
| 41 | Ananindeua | | | | |
| 42 | Serra | :white_check_mark: | | | |
| 43 | Niterói | | | | |
| 44 | Belford Roxo | | | | |
| 45 | Campos dos Goytacazes Campos dos Goytacazes | | | | |
| 46 | Vila Velha | :white_check_mark: | | | |
| 47 | Florianópolis | :white_check_mark: | | | https://github.com/okfn-brasil/diario-oficial/pull/17 |
| 48 | Caxias do Sul | | | | |
| 49 | Macapá | | | | |
| 50 | Mauá | | | | |
| 51 | São João de Meriti | | | | |
| 52 | São José do Rio Preto | | | | |
| 53 | Santos | :soon: | | | https://github.com/okfn-brasil/diario-oficial/pull/14 |
| 54 | Mogi das Cruzes | | | | |
| 55 | Betim | | | | |
| 56 | Diadema | | | | |
| 57 | Campina Grande | | | | |
| 58 | Jundiaí | | | | |
| 59 | Maringá | | | | |
| 60 | Montes Claros | :soon: | | | https://github.com/okfn-brasil/diario-oficial/pull/26 |
| 61 | Piracicaba | | | | |
| 62 | Carapicuíba | | | | |
| 63 | Olinda | | | | |
| 64 | Cariacica | :white_check_mark: | | | |
| 65 | Rio Branco | | | | |
| 66 | Anápolis | | | | |
| 67 | Bauru | | | | |
| 68 | Vitória | :white_check_mark: | | | |
| 69 | Caucaia | | | | |
| 70 | Itaquaquecetuba | | | | |
| 71 | São Vicente | | | | |
| 72 | Bandeira caruaru.jpg Caruaru | | | | |
| 73 | Vitória da Conquista | | | | |
| 74 | Blumenau | | | | |
| 75 | Franca | :white_check_mark: | | | https://github.com/okfn-brasil/diario-oficial/pull/5 |
| 76 | Pelotas | | | | |
| 77 | Ponta Grossa | | | | https://github.com/okfn-brasil/diario-oficial/pull/45 |
| 78 | Canoas | | | https://github.com/okfn-brasil/diario-oficial/issues/10 | |
| 79 | Petrolina | | | | |
| 80 | Boa Vista | | | | |
| 81 | Ribeirão das Neves | | | | |
| 82 | Paulista | | | | |
| 83 | Uberaba | | | | |
| 84 | Cascavel | | | | |
| 85 | Guarujá | | | | |
| 86 | Praia Grande | | | | |
| 87 | Taubaté | | | | |
| 88 | São José dos Pinhais | | | | |
| 89 | Limeira | | | | |
| 90 | Petrópolis | | | | |
| 91 | Camaçari | | | | |
| 92 | Santarém | | | | |
| 93 | Mossoró | | | | |
| 94 | Suzano | | | | |
| 95 | Palmas | :white_check_mark: | | | https://github.com/okfn-brasil/diario-oficial/pull/1 |
| 96 | Governador Valadares | :soon: | | | https://github.com/okfn-brasil/diario-oficial/pull/19 |
| 97 | Taboão da Serra | | | | |
| 98 | Santa Maria | | | | |
| 99 | Gravataí | | | | |
| 100 | Várzea Grande | | | | |
| XXX | Foz do Iguaçu | | | | https://github.com/okfn-brasil/diario-oficial/pull/34 https://github.com/okfn-brasil/diario-oficial/pull/27 |
| XXX | Araguaina | | | | https://github.com/okfn-brasil/diario-oficial/pull/3 |

**Comment by rennerocha** [comment]
How about including this list as a CITIES.md file in the repository? It'd be easier to update it so we can track better what city needs to be done next. I can't update your comment with Salvador spider for example.

**Comment by alfakini** [comment]
Including it right now!

**Comment by anapaulagomes** [comment]
Good idea! The no. 34 is outdated (the PR was merged).

**Comment by Irio** [comment]
Closing it since the tracking was moved to a repository file in #50.
