### ISSUE TITLE
Cities that depend on js

### ISSUE THREAD

**Issue by chicocvenancio** [okfn-brasil/diario-oficial#54]
What should be our approach to cities that depend on JS? I'm more used to Selenium and a browser, but we probably should define a single approach.

**Comment by cuducos** [comment]
Do you have any example in mind? There is Splash (thanks @rennerocha) and Selenium… but in most cases I'd say we could try to reproduce whatever JS in doing (for example, embedding session/cookies in a AJAX request)… so I think there's not a single answer here, but a case by case analysis.

**Comment by chicocvenancio** [comment]
São Luís at http://www.semad.saoluis.ma.gov.br:8090/easysearch/

**Comment by cuducos** [comment]
Wow, this web site is really terrible for transparency purposes : ( I guess the unique ID is only viable interacting with the web site via JS indeed in that case.

**Comment by Irio** [comment]
@chicocvenancio A few weeks ago I configured scrapy-splash for a contributor willing to write a crawler for a js-heavy page. You can find the commit [here](https://github.com/okfn-brasil/diario-oficial/commit/daa5731dc9ee96340a91e2bda7d81b4f59aab2ff).

**Comment by silasalvares** [comment]
Hey guys, i'm trying to build the Aracaju city spider and i'm stuck on the same problem. Could you have a look in the page? http://sga.aracaju.se.gov.br:5011/legislacao/faces/diario_form_pesq.jsp.
Whats the best approach in this case? To use a browser testing tool?

**Comment by cuducos** [comment]
@silasalvares, the proper way to do it is [using Splash](https://github.com/okfn-brasil/diario-oficial/issues/54#issuecomment-392287528), as @irio just mentioned.
