### ISSUE TITLE
Common platform used by many municipalities

### ISSUE THREAD

**Issue by beothorn** [okfn-brasil/diario-oficial#65]
While looking for gazettes for Paranavaí the official site redirects to a portal that seems to be used by lots of smaller municipalities.

http://www.diariomunicipal.com.br

This portal even allow to search for terms like "Dispensa"

http://www.diariomunicipal.com.br/amp/pesquisar?entidadeUsuaria=&titulo=Dispensa&nome_orgao=&dataInicio=01%2F05%2F2018&dataFim=31%2F05%2F2018&Enviar=&_token=aAfXBvwcSMnp4lRq1qoriAGxW9rav7iawfmpUeHGLMk

Only problem is that the result is not a single pdf, but a page for each result. I believe that another pipeline would be needed for scraping this website.
Although i haven't found any city on the top 100 using this portal, maybe it would be worth scraping it given the amount of cities that uses it.

What do you think?

**Comment by beothorn** [comment]
Also it seems they have a rest API

http://www.diariomunicipal.com.br/amp/rest/materia/search-materias?entidadeUsuaria=&titulo=&nome_orgao=&dataInicio=2018-05-01&dataFim=2018-05-31&sEcho=1&iColumns=4&sColumns=entidade%2Ctitulo%2Corgao%2CdataCirculacao&iDisplayStart=0&iDisplayLength=10&mDataProp_0=0&sSearch_0=&bRegex_0=false&bSearchable_0=false&bSortable_0=false&mDataProp_1=1&sSearch_1=&bRegex_1=false&bSearchable_1=false&bSortable_1=false&mDataProp_2=2&sSearch_2=&bRegex_2=false&bSearchable_2=false&bSortable_2=false&mDataProp_3=3&sSearch_3=&bRegex_3=false&bSearchable_3=false&bSortable_3=false&sSearch=&bRegex=false&iSortingCols=0&_=1527800170218

**Comment by Irio** [comment]
Hey there, @beothorn

As stated in the [contribution guidelines](https://github.com/okfn-brasil/diario-oficial/blob/6526364bc2471a72c3adf1196e8396cc058ae844/CONTRIBUTING.md#contributing), we intend to collect from official sources.

For instance, smaller municipalities from the state of Espírito Santo decided to delegate the task of publishing their gazettes to Associação dos Municípios do Estado do Espírito Santo. When such thing happens, we look for two requirements. Let's take [Laranja da Terra (ES)](http://www.laranjadaterra.es.gov.br/) as an example:

- [x] The official website links to the aggregator when mentioning its gazette.

<img width="683" alt="bildschirmfoto 2018-06-02 um 15 00 08" src="https://user-images.githubusercontent.com/667753/40879410-bfb8e036-6675-11e8-96ef-841f8fb793dd.png">

- [x] A municipal law staging the aggregator as an authorized publisher. As http://www3.laranjadaterra.es.gov.br/norma.aspx?id=817.

<img width="1128" alt="bildschirmfoto 2018-06-02 um 15 01 28" src="https://user-images.githubusercontent.com/667753/40879420-e067c306-6675-11e8-97e8-ea68cd83b330.png">

When we can find examples of both, we're more than happy to integrate with the aggregator, as we did with the [previous website](https://github.com/okfn-brasil/diario-oficial/blob/6526364bc2471a72c3adf1196e8396cc058ae844/processing/data_collection/gazette/spiders/es_associacao_municipios.py).

**Comment by antoniovendramin** [comment]
Hi,
in the case of Paranavaí, we found the law stating the aggregator as an authorized publisher ([http://www.controlemunicipal.com.br/inga/sistema/arquivos/12101/040817154719_lei_municipal_46042017__institui_o_diario_oficial_dos_municipios_do_parana_como_veiculo_oficial_pdf.pdf](url)).
Now the problem is with the format, that is a single HTML page and not a PDF.
Do you have some suggestion how we could work on this? We believe that the pipeline must be changed, but we are not sure how.

**Comment by vitorbaptista** [comment]
Just to add, the diário oficial from Rio de Janeiro has a similar "problem". Although the spider we created extracts the PDFs, it does have a version in HTML, which would be much easier to parse than OCRing a PDF file.

**Comment by rennerocha** [comment]
Even if the HTML content is available (and easier to parse its content). I believe it is worthy to also download the PDF, so it can be made available in this format as well (if the effort isn't too large).

**Comment by antoniovendramin** [comment]
@rennerocha, do you suggest download the HTML content and convert to PDF? Because there is not available a PDF version.

**Comment by rennerocha** [comment]
@antoniovendramin I understood that the PDF is also available for download! In this case, I don't see any gain generating a PDF for the content.
