### ISSUE TITLE
Introduce middleware to ignore requests of pages alread scraped

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/diario-oficial#86]
To avoid download already scraped items, we could include this middleware:
https://github.com/scrapy-plugins/scrapy-deltafetch

This middleware ignore requests to pages containing items seen in previous crawls.

Yesterday I talked about https://github.com/okfn-brasil/diario-oficial/pull/67, we need to test the middleware with this kind of requests to see how it works.

**Comment by vitorbaptista** [comment]
@rennerocha I read the `scrapy-deltafetch` code and I think it might cause us problems. The logic is pretty simple: save the request URL that generated and scrapy Items in a DB, and don't allow this URL to be requested again.

This will only work iff the items on each page never change, which might not be true for all cases. For example, a paginated list of products. Today, the page 1 contains a set of items. In a few days, these items might be different, but we won't extract the data again as we've already seen page 1.

This might not be the case for all our scrapers, but there still might be some that have this problem.

What do you think?

**Comment by rennerocha** [comment]
@vitorbaptista I believe we need to test it. Maybe some spiders (mainly the ones that use VIEWSTATE or something similar) won't work, but most of them are simple enough and I believe it will work without problems.

I did some small tests with Jundiaí spider and it worked well. I will try to continue my testing with other spiders so we can see if it feasible or not to enable this middleware.

**Comment by jvanz** [comment]
I would like to have this in place before run the spider in the production environment  (0.9.0 milestone). I just quick reviewed the project documentation and, despite of the points raised by @vitorbaptista, I think it maybe be viable. Even if the middleware does not work 100% of the time, it may be useful to reduce waste of resources (network traffic and CPU cicles). We can even send patches to the project or fork a version for ourselves and adapt to our needs. 

The first possible problem I can see is that it use a directory to keep track of the state. Which can be a little bit challange in a cloud enviroment with possible multiples servers. Any way, I'll try to work on this in the next days.

**Comment by jvanz** [comment]
As the lib uses the URL to check if the spider downloaded the item or not, we can end in the situation of missing some file or re download a file (as pointed by @vitorbaptista ). The only way to ensure that we already have the file is using the md5 of it. But we do not have access to that information before downloading the file. 

I believe that in the production environment we can keep the middleware active and rerun the spider to get all the files once in a while. Thus, I believe, we ensure to get all the files and avoid to re download all the files every time.

**Comment by jvanz** [comment]
Another option: https://github.com/TeamHG-Memex/scrapy-crawl-once

Very similar to scrapy-deltafetch
