### ISSUE TITLE
Clearly handle integration tests and code style check in Makefile and CI

### ISSUE THREAD

**Issue by cuducos** [okfn-brasil/diario-oficial#97]
As discussed in https://github.com/okfn-brasil/diario-oficial/pull/84#discussion_r203755465

**Comment by Irio** [comment]
Since integration tests removed recently removed, the travis.yml file was also changed. 

https://github.com/okfn-brasil/diario-oficial/pull/131/files#diff-354f30a63fb0907d4ad57269548329e3

I believe that should have also fixed this issue here.
